name: "Roam Research backup"

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/10 * * * *" #doesn't actually consistently run every 10 min =\

jobs:
  backup:
    #runs-on: "Ubuntu-20.04" # trying to workaound random crashes on linux
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 15
    steps:
      - name: Checkout notes repo
        uses: actions/checkout@v3.5.2
        with:
          repository: ${{ secrets.targetRepo }}
          token: ${{ secrets.roamPat }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v4.6.0
        with:
          python-version: 3.8
      
      - name: Setup dependencies
        run: |
          #wget -qO /tmp/jet.zip https://github.com/borkdude/jet/releases/download/v0.0.13/jet-0.0.13-linux-amd64.zip
          #unzip /tmp/jet.zip -d /tmp
          #sudo mv /tmp/jet /usr/local/bin/jet
          # https://github.com/MatthieuBizien/roam-to-git/pull/112
          pip install "git+https://github.com/Stvad/roam-to-git"
# removing as it logs sensetive information
#     - name: Download markdown images for previous backup
        # not commiting the changes to md files with this =\, should be possible to recover things by deconding the base64 of file names 
#        run: npx markdown-backup "markdown/**/*.md"
      - name: Run backup
        run: |
          roam-to-git . --formats json edn #markdown
          # no markdown for now bc I have page names that are too long and that crashes the backup
        env:
          ROAMRESEARCH_USER: ${{ secrets.roamEmail }}
          ROAMRESEARCH_PASSWORD: ${{ secrets.roamPassword }}
          ROAMRESEARCH_DATABASE: ${{ secrets.roamDatabase }}
          
